Rails/library/config/routes.rb
Rails.application.routes.draw do
  
  
  	root 'authors#index'

  	get 'signup' => 'users#new'

  	resource :session
  	
  	resources :users do
  		resources :lendings
  	end

  	resources :authors do
  		resources :books
  	end
end

Rails/library/app/views/layouts/_top_bar.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Library</li>
      <li><%= link_to 'Authors', authors_path %></li>
       <li><%= link_to 'User-Liste', users_path %></li>
       <% if current_user %>
       <li><%= link_to 'Meine Ausleih-Liste', user_lendings_path(current_user.id) %></li>

       <% end %>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
    <% if current_user %>
      <%= current_user.login.capitalize %>
        <%= link_to 'LogOut', session_path, method: :delete %>
        <% else %>
    <li><%= link_to 'Sign Up', signup_path %></li>
    <li><%= link_to 'Sign In', new_session_path %></li>
        <% end %>
    </ul>
  </div>
</div> 

Rails/library/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <%= render 'layouts/top_bar' %>
    <%= yield %>

  </body>
</html>