Rails/Projekte/foodfit/config/routes.rb
Rails.application.routes.draw do
  

    root 'application#index'
	   get 'signup' => 'users#new'
     get 'overview' => 'application#overview'
     get 'diet1' => 'application#lowcarb'
     get 'diet2' => 'application#lowfat'
     get 'diet3' => 'application#trennkost'

  resources :chats
  resources :profiles
  resources :calculators   
  resources :users
  resources :bodies
  resource :session

  resources :foods do
  	resources :fooddiaries
  end

  resources :sports do
  	resources :sportdiaries
  end
end

Rails/Projekte/foodfit/app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :calculator
  belongs_to :food
  belongs_to :fooddiary
  belongs_to :sport
  belongs_to :sportdiary
end

Rails/Projekte/foodfit/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :require_signin

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :calculator_id, :food_id, :fooddiary_id, :sport_id, :sportdiary_id)
    end
end

Rails/Projekte/foodfit/app/views/profiles/_food.html.erb
<% food_id = Fooddiary.where(user_id: current_user.id).collect { |y| y.food_id } %>

<% if food_id.count > 0 %>
 <div class="search" style="width:30%"><%= form_tag(food_fooddiaries_path(food_id), :method => "get", id:"search-form") do %>
 <%= text_field_tag :search, params[:search], placeholder: "Datum eingeben" %>
 <center><%= submit_tag "Suchen", :datum => nil, class: 'primary button' %></center>
 <% end %> 

<br>

<br><br>

</div>

<br><br><br><br><br><br>

<%= link_to 'Einträge Bearbeiten', food_fooddiaries_path(food_id), class: 'warning button' %>

<table>
  <thead>
    <tr>
      <th style="width:14.285714286%">Datum</th>
      <th style="width:14.285714286%">Lebensmittel</th>
      <th style="width:14.285714286%">Anzahl</th>
      <th style="width:14.285714286%">Eiweiß</th>
      <th style="width:14.285714286%">Fett</th>
      <th style="width:14.285714286%">Kohlenhydrate</th>
      <th style="width:14.285714286%">Kalorien</th>
    </tr>
  </thead>

  <% ary6 = User.where(id: current_user.id).collect { |o| o.name } %>
  <% ary7 = Body.where(user_id: current_user.id).collect { |s| s.weigth } %>
  <% ary8 = Fooddiary.where(user_id: current_user.id).collect { |t| t.name } %>
  <% ary9 = Fooddiary.where(user_id: current_user.id).collect { |u| u.anzahl } %>
  <% ary10 = Sportdiary.where(user_id: current_user.id).collect { |v| v.name } %>
  <% ary11 = Sportdiary.where(user_id: current_user.id).collect { |w| w.anzahl } %>
  <% ary12 = Fooddiary.where(user_id: current_user.id).order(:datum).collect { |x| x.datum } %>
  <% ary13 = Fooddiary.where(user_id: current_user.id).collect { |a| a.anzahl } %>
  <% ary14 = Fooddiary.where(user_id: current_user.id).collect { |b| b.eiweiß } %>
  <% ary15 = Fooddiary.where(user_id: current_user.id).collect { |c| c.fett } %>
  <% ary16 = Fooddiary.where(user_id: current_user.id).collect { |d| d.kohlenhydrate } %>
  <% ary17 = Fooddiary.where(user_id: current_user.id).collect { |e| e.kalorien } %>

<% i = 0 %>
<% while i < ary12.count %>

  <tbody>
    <tr>
        <td><%= ary12[i] %></td>
        <td><%= ary8[i] %></td>
        <td><%= ary13[i] %></td>
        <td><%= (ary14[i] * ary13[i]).round(2) %></td>
        <td><%= (ary15[i] * ary13[i]).round(2) %></td>
        <td><%= (ary16[i] * ary13[i]).round(2) %></td>
        <td><%= ary17[i] * ary13[i] %></td>
        <% i = i + 1 %>
      <% end %>
      </tr>
  </tbody>
</table>
<% end %>

Rails/Projekte/foodfit/app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :calculator_id %>
    <%= f.text_field :calculator_id %>
  </div>

  <div class="field">
    <%= f.label :food_id %>
    <%= f.text_field :food_id %>
  </div>

  <div class="field">
    <%= f.label :fooddiary_id %>
    <%= f.text_field :fooddiary_id %>
  </div>

  <div class="field">
    <%= f.label :sport_id %>
    <%= f.text_field :sport_id %>
  </div>

  <div class="field">
    <%= f.label :sportdiary_id %>
    <%= f.text_field :sportdiary_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Projekte/foodfit/app/views/profiles/_sport.html.erb
<% sport_id = Sportdiary.where(user_id: current_user.id).collect { |x| x.sport_id } %>

<% if sport_id.count > 0 %>
 <div class="search" style="width:30%"><%= form_tag(sport_sportdiaries_path(sport_id), :method => "get", id:"search-form") do %>
 <%= text_field_tag :search, params[:search], placeholder: "Datum eingeben" %>
 <center><%= submit_tag "Suchen", :datum => nil, class: 'primary button' %></center>
 <% end %> 

<br>

<br><br>

</div>

<br><br><br><br><br><br>

<%= link_to 'Einträge Bearbeiten', sport_sportdiaries_path(sport_id), class: 'warning button' %>

<table>
  <thead>
    <tr>
      <th style="width:25%">Datum</th>
      <th style="width:25%">Übung</th>
      <th style="width:25%">Anzahl/Dauer</th>
      <th style="width:25%">Kalorien</th>
    </tr>
  </thead>

  <% ary10 = Sportdiary.where(user_id: current_user.id).collect { |v| v.name } %>
  <% ary11 = Sportdiary.where(user_id: current_user.id).collect { |w| w.anzahl } %>
  <% ary18 = Sportdiary.where(user_id: current_user.id).collect { |g| g.kalorien } %>
  <% ary19 = Sportdiary.where(user_id: current_user.id).collect { |h| h.datum } %>

<% i = 0 %>
<% if ary19.count > 0 %>
<% while i < ary19.count %>

  <tbody>
    <tr>
        <td><%= ary19[i] %></td>
        <td><%= ary10[i] %></td>
        <td><%= ary11[i] %></td>
        <td><%= ary18[i] * ary11[i] %></td>
        <% i = i + 1 %>
      <% end %>
      </tr>
  </tbody>
</table>
  <% end %>
  
<br><br><br>

<center>

<% end %>

Rails/Projekte/foodfit/app/views/profiles/_success.html.erb
<center><h1>Erfolge <%= image_tag("success1.jpg", size: "225") %></h1>



      <% ary1 = User.where(id: current_user.id).collect { |o| o.start_weight } %>
      <% ary4 = User.where(id: current_user.id).collect { |p| p.dream_weight } %>
      <% ary2 = Body.where(user_id: current_user.id).collect { |r| r.datum } %>
      <% ary3 = Body.where(user_id: current_user.id).collect { |s| s.weigth } %>
      <% ary5 = User.where(id: current_user.id).collect { |q| q.created_at } %>
      <% u = Body.where(user_id: current_user.id).order("id DESC").limit(2) %>
        
<table border="2" style="width:80%">
  <thead>
    <tr>
      <th width="18%">Start-Datum</th>
      <th width="18%">Startgewicht</th>
      <th width="18%">Aktuelles Gewicht</th>
      <th width="18%">Zielgewicht</th>
      <th width="18%">Fehlt zum Ziel</th>
    </tr>
  </thead>


  <tbody>
           <tr>
           <td><%= ary5.first %></td>
           <td><%= ary1.first %> Kg</td>
           <% if ary3.any? %>
           <td><%= ary3.last %> Kg</td> 
           <% else %>
           <td><%= "Noch keine Eingabe vorhanden" %></td>
           <% end %>
           <td><%= ary4.first %> Kg</td>
           <% if ary3.any? %>
           <td><%= ary3.last - ary4.first %> Kg</td>
           <% else %>
           <td><%= "Noch keine Rechnung möglich" %></td>
           <% end %>
           </tr>
        </tbody>
</table>

<%= image_tag("success3.jpg", width: "450") %>

<table border="2" style="width:80%">
  <thead>
    <tr>
    <th width="18%">Datum</th>
    <th width="18%">Letztes gemessenes Gewicht</th>
    <th width="18%">Aktuelles Gewicht</th>
    <th width="18%">Differenz zur letzten Messung</th>
    <th width="18%">Differenz vom aktuellen zum Startgewicht</th>
    </tr>
  </thead>

  <tbody>
          <tr>
          <% if Body.where(user_id: current_user.id).collect { |q| q.weigth }.count > 1 %>
             <td><%= ary2.last %></td>
             <td><%= u[1].weigth %> Kg</td>
             <td><%= ary3.last %> Kg</td>
             <td><%= u[1].weigth - ary3.last %> Kg</td>
             <td><%= ary1.first - ary3.last %> Kg</td>
          <% else %>
              <% if ary2.any? %>
              <td><%= ary2.last %></td>
              <% else %>
              <td><%= "Noch keine Eingabe vorhanden" %></td>
              <% end %>
              <td><%= "Noch keine Eingabe vorhanden" %></td>
              <% if ary3.any? %>
              <td><%= ary3.last %></td>
              <% else %>
              <td><%= "Noch keine Eingabe vorhanden" %></td>
              <% end %>
              <td><%= "Noch keine Rechnung möglich" %></td>
              <% if ary3.any? %>
              <td><%= ary1.first - ary3.last %> Kg</td>
              <% else %>
              <td><%= "Noch keine Rechnung möglich" %></td>
           <% end %>
          <% end %>
          </tr>
  </tbody>
</table>


</div>

</center>

Rails/Projekte/foodfit/app/views/profiles/_useredit.html.erb
<div class="right4">
<%= image_tag('profile.jpg') %>
</div>

<center><br><br>
<table style="width:35%; font-size:18px; text-align:left">
  <tr>
    <th>Name:</th>
    <th style="font-size:18px"><%= User.where(id: current_user.id).collect { |a| a.name }.first.capitalize %></th>
  </tr>

  <tr>
    <th>Email:</th>
    <th style="font-size:18px"><%= User.where(id: current_user.id).collect { |b| b.email }.first %></th>
  </tr>

  <tr>
    <th>Alter:</th>
    <th style="font-size:18px"><%= User.where(id: current_user.id).collect { |c| c.age }.first %></th>
  </tr>

  <tr>
    <th>Start-Gewicht:</th>
    <th style="font-size:18px"><%= User.where(id: current_user.id).collect { |d| d.start_weight }.first %></th>
  </tr>

  <tr>
    <th>Ziel-Gewicht:</th>
    <th style="font-size:18px"><%= User.where(id: current_user.id).collect { |e| e.dream_weight }.first %></th>
  </tr>

  <tr>
    <th>Größe:</th>
    <th style="font-size:18px"><%= User.where(id: current_user.id).collect { |f| f.height }.first %></th>
  </tr>
</table>

<br>

<%= link_to 'Daten bearbeiten', edit_user_path(id: current_user.id), class: 'warning button' %>
</center>

Rails/Projekte/foodfit/app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

Rails/Projekte/foodfit/app/views/profiles/index.html.erb
<center><h1><u>Profil von <span style="color:red"><%= current_user.name.capitalize %></span></u></h1></center><br>

<ul class="tabs" data-tabs id="example-tabs">
  <li class="tabs-title is-active"><a href="#panel1" aria-selected="true"><h5><b style="color:black">Profil-Übersicht</b></h5></a></li>
  <li class="tabs-title"><a href="#panel2"><h5><b style="color:black">Lebensmittel-Tagebuch</b></h5></a></li>
  <li class="tabs-title"><a href="#panel3"><h5><b style="color:black">Sport-Tagebuch</b></h5></a></li>
  <li class="tabs-title"><a href="#panel4"><h5><b style="color:black">Erfolge</b></h5></a></li>
</ul>
<div class="tabs-content" data-tabs-content="example-tabs">
  <div class="tabs-panel is-active" id="panel1">

<%= render 'useredit' %>

  </div>

  <div class="tabs-panel" id="panel2">

<%= render 'food' %>

</div>

  <div class="tabs-panel" id="panel3">
    
<%= render 'sport' %>

</div>

  <div class="tabs-panel" id="panel4">

<%= render 'success' %>

  </div>

Rails/Projekte/foodfit/app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

Rails/Projekte/foodfit/app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<p>
  <strong>Calculator:</strong>
  <%= @profile.calculator %>
</p>

<p>
  <strong>Food:</strong>
  <%= @profile.food %>
</p>

<p>
  <strong>Fooddiary:</strong>
  <%= @profile.fooddiary %>
</p>

<p>
  <strong>Sport:</strong>
  <%= @profile.sport %>
</p>

<p>
  <strong>Sportdiary:</strong>
  <%= @profile.sportdiary %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>