Rails/Projekte/library/config/routes.rb
Rails.application.routes.draw do
  
  root "authors#index"		

  get 'signup' => 'users#new'

  		
  	resource :session
  		
  	resources :users 

		resources :lendings

		resources :authors do 
  			resources :books
  		end
end

Rails/Projekte/library/app/views/layouts/_flash_messages.html.erb
<div class="panel">

<% flash.each do |key, value| %>
	<%= content_tag(:p, value, :class => "flash_#{key}") %> 
	<%#key = alert oder notice %>
<% end %>

</div>

Rails/Projekte/library/app/views/layouts/_side_bar.html.erb
<h4>Sidebar</h4>

Rails/Projekte/library/app/views/layouts/_top_bar.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Library</li>
      <li><%= link_to 'Authors', root_path %></li>
       <li><%= link_to 'User-Liste', users_path %></li>
       <li><%= link_to 'Ausleih-Liste', lendings_path %></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
    <% if current_user %>
      <%= current_user.login.capitalize %>
        <%= link_to 'LogOut', session_path, method: :delete %>
        <% else %>
    <li><%= link_to 'Sign Up', signup_path %></li>
    <li><%= link_to 'Sign In', new_session_path %></li>
        <% end %>
    </ul>
  </div>
</div>

Rails/Projekte/library/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="row">
      <div class="row float-right">



      </div>

      <div class="clearfix">
      </div>

        <%= render 'layouts/top_bar' %>

      <div class="row">
        <%= render 'layouts/flash_messages' %>
        
        <div class="medium-1 columns">
          
        </div>
        <div class="medium-11 columns">
         
          <%= yield %>
        </div>  
      </div>
</div>

  </body>
</html>